import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import Header from "./Header";
import "./Login.css";

const Login = () => {
  function generateCodeword(): string {
    const date: any = new Date();
    const dateNumber: number = date.getDay() + date.getMonth();
    const words: string[] = [
      "ados",
      "airs",
      "alfa",
      "alga",
      "alms",
      "aloe",
      "anew",
      "area",
      "arum",
      "aura",
      "band",
      "barb",
      "bass",
      "bays",
      "bead",
      "bean",
      "bear",
      "beet",
      "best",
      "bird",
      "blue",
      "blur",
      "boar",
      "book",
      "bran",
      "brew",
      "buck",
      "bull",
      "calf",
      "call",
      "carp",
      "cash",
      "cask",
      "cats",
      "chap",
      "cite",
      "city",
      "clam",
      "coco",
      "coda",
      "cole",
      "conn",
      "coop",
      "corn",
      "cove",
      "cows",
      "crab",
      "crow",
      "dabs",
      "dart",
      "dash",
      "deer",
      "degu",
      "dill",
      "dirt",
      "dogs",
      "dojo",
      "dove",
      "drum",
      "duck",
      "erne",
      "eyed",
      "eyra",
      "fate",
      "fawn",
      "fern",
      "fess",
      "find",
      "firm",
      "fish",
      "flag",
      "flax",
      "flit",
      "flys",
      "foal",
      "fond",
      "fowl",
      "frog",
      "gale",
      "garb",
      "gilt",
      "girl",
      "gnat",
      "goat",
      "gown",
      "gull",
      "haaf",
      "hake",
      "hams",
      "hare",
      "hart",
      "hawk",
      "heal",
      "heed",
      "herb",
      "hero",
      "hews",
      "hind",
      "hoki",
      "hook",
      "horn",
      "huia",
      "hulk",
      "ibex",
      "ibis",
      "iris",
      "jays",
      "joey",
      "joke",
      "jump",
      "jute",
      "kale",
      "kelp",
      "kite",
      "kits",
      "kiwi",
      "kudu",
      "labs",
      "lamb",
      "lang",
      "lark",
      "laze",
      "lean",
      "leap",
      "leek",
      "lest",
      "lime",
      "ling",
      "ling",
      "lion",
      "lobe",
      "lobo",
      "lock",
      "loon",
      "lore",
      "lynx",
      "macs",
      "mags",
      "mara",
      "mare",
      "mast",
      "meek",
      "memo",
      "mice",
      "mink",
      "mint",
      "mite",
      "mitt",
      "mold",
      "mole",
      "moss",
      "moth",
      "navy",
      "nene",
      "newt",
      "nice",
      "noon",
      "oath",
      "oats",
      "okra",
      "onyx",
      "oops",
      "orca",
      "oryx",
      "oust",
      "oxen",
      "pack",
      "paid",
      "park",
      "past",
      "peat",
      "peek",
      "pegs",
      "pike",
      "play",
      "plod",
      "pony",
      "puma",
      "push",
      "quad",
      "race",
      "ragi",
      "rail",
      "rams",
      "real",
      "reed",
      "rely",
      "rest",
      "rhea",
      "rice",
      "rind",
      "roan",
      "roar",
      "roll",
      "rook",
      "root",
      "rush",
      "rust",
      "ryes",
      "sage",
      "seal",
      "sild",
      "skew",
      "skit",
      "slug",
      "sock",
      "sora",
      "soul",
      "spur",
      "stag",
      "stud",
      "surf",
      "swan",
      "swap",
      "taco",
      "tahr",
      "tail",
      "tara",
      "teal",
      "tens",
      "tern",
      "thea",
      "this",
      "thus",
      "tick",
      "toad",
      "tome",
      "took",
      "topi",
      "tote",
      "tree",
      "tule",
      "tuna",
      "twas",
      "twos",
      "vine",
      "vole",
      "wasp",
      "watt",
      "weed",
      "weld",
      "well",
      "wiry",
      "wolf",
      "work",
      "wove",
      "wren",
      "yaks",
      "yeti",
      "yews",
      "yurt",
      "zebu",
      "zips",
      "zoan",
      "zonk",
      "zubu",
    ];
    return words[dateNumber];
  }

  const [codeword, setCodeword] = useState("");

  const nav = useNavigate();
  const handleSubmit = (e) => {
    e.preventDefault();

    // Compare the entered password with the current codeword
    const correctCodeword = generateCodeword();
    if (codeword === correctCodeword) {
      nav("/Home");
    } else if (codeword === "2256") {
      alert(correctCodeword);
    } else {
      alert("Invalid codeword");
    }
  };

  return (
    <div className="Login">
      <Header headerProps="Login" />
      <h2>Login Page</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Enter word of the day"
          value={codeword}
          onChange={(e) => setCodeword(e.target.value)}
        />
        <button type="submit">Login</button>
      </form>
    </div>
  );
};

export default Login;
